spring:
  cloud:
    vault:
      authentication: APPROLE
      app-role:
        role-id: 39dda5e7-75e6-7720-b7af-f66724d7f3d6
#        secret-id: be68f54a-af19-c731-33a3-c4b6521b2332
        role: admin
        app-role-path: approle
      uri: http://localhost:8200
      connection-timeout: 5000
      read-timeout: 15000
  config:
    import: vault://secret/demo
mykey: ${mykey}
hello.world: ${hello.world}
#actuator
management.endpoint.restart.enabled: true
management.endpoints.web.exposure.include: restart,health
        